name: Deploy to Cloudflare

on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Wrangler
        run: npm i -g wrangler@4

      # シークレットを Cloudflare に投入
      - name: Put CF Secrets
        run: |
          wrangler secret put CHANNEL_SECRET       --value "${{ secrets.CHANNEL_SECRET }}"       --non-interactive
          wrangler secret put CHANNEL_ACCESS_TOKEN --value "${{ secrets.CHANNEL_ACCESS_TOKEN }}" --non-interactive
          wrangler secret put GEMINI_API_KEY       --value "${{ secrets.GEMINI_API_KEY }}"       --non-interactive
          wrangler secret put MY_USER_ID           --value "${{ secrets.MY_USER_ID }}"           --non-interactive
          # SYSTEM_PROMPT は任意
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

      - name: Deploy Worker
        run: wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}